Traceback (most recent call last):
  File "/Users/eunjikim/Library/Caches/pypoetry/virtualenvs/webtoon-data-tpyUZrQj-py3.9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/eunjikim/Library/Caches/pypoetry/virtualenvs/webtoon-data-tpyUZrQj-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/eunjikim/Library/Caches/pypoetry/virtualenvs/webtoon-data-tpyUZrQj-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/eunjikim/Library/Caches/pypoetry/virtualenvs/webtoon-data-tpyUZrQj-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/eunjikim/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/eunjikim/Library/Caches/pypoetry/virtualenvs/webtoon-data-tpyUZrQj-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/eunjikim/Library/Caches/pypoetry/virtualenvs/webtoon-data-tpyUZrQj-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/eunjikim/Library/Caches/pypoetry/virtualenvs/webtoon-data-tpyUZrQj-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import webtoon_data

print(webtoon_data.__version__)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/var/folders/wt/01j65jj52hb2v502kfxlrq4r0000gn/T/ipykernel_84905/4094595133.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mimport[0m [0mwebtoon_data[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mprint[0m[0;34m([0m[0mwebtoon_data[0m[0;34m.[0m[0m__version__[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'webtoon_data'
ModuleNotFoundError: No module named 'webtoon_data'

